# docker compose for running the application with the database

services:
  db:
    image: postgres:12
    hostname: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sge2

  web:
    build: .
    hostname: web
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/sge2
    depends_on:
      - db

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - web
